version: "3.8"

services:
  public-api:
    build: ./
    container_name: public-api
    restart: unless-stopped
    environment:
      - PORT=14020
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.private-api.loadbalancer.server.port=14020"
      - "traefik.http.routers.private-api.rule=Host(`api.salvatoreemilio.it`) ||
        Host(`www.api.salvatoreemilio.it`)"
      - "traefik.http.routers.private-api.tls.certresolver=myresolver"
      - "traefik.http.routers.private-api.entrypoints=websecure"

networks:
  default:
    external: true
    name: se_default
