version: "3.8"

services:
  public-api:
    image: salvatoreemilio/salvatoreemilio.it_public-api:latest
    container_name: public-api
    restart: unless-stopped
    environment:
      - LOG_LEVEL=DEBUG
      - INTERNAL_API_HOST=internal-api
      - INTERNAL_API_PORT=14010
      - GUNICORN_PORT=14021
      - KEYCLOAK_REALM_NAME=se
      - KEYCLOAK_URL=https://login.salvatoreemilio.it/auth/
      - KEYCLOAK_CLIENT_ID=api-auth
      - KEYCLOAK_CLIENT_SECRET_KEY=${KEYCLOAK_CLIENT_SECRET_KEY}
      - KEYCLOAK_SERVICE_ACCOUNT_CLIENT_ID=api-service-account
      - KEYCLOAK_SERVICE_ACCOUNT_CLIENT_SECRET_KEY=${KEYCLOAK_SERVICE_ACCOUNT_CLIENT_SECRET_KEY}
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
  public-api_nginx:
    image: nginx
    container_name: public-api_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      - public-api
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.public-api_nginx.loadbalancer.server.port=14020"
      - "traefik.http.routers.public-api_nginx.rule=Host(`api.salvatoreemilio.it`) || Host(`www.api.salvatoreemilio.it`)"
      - "traefik.http.routers.public-api_nginx.tls.certresolver=myresolver"
      - "traefik.http.routers.public-api_nginx.entrypoints=websecure"

networks:
  default:
    external: true
    name: se_default
