version: "3.8"

services:
  public-api:
    image: salvatoreemilio/salvatoreemilio.it_public-api:latest
    container_name: public-api
    restart: unless-stopped
    environment:
      - KEYCLOAK_CLIENT_SECRET_KEY=${KEYCLOAK_CLIENT_SECRET_KEY}
      - KEYCLOAK_SERVICE_ACCOUNT_CLIENT_SECRET_KEY=${KEYCLOAK_SERVICE_ACCOUNT_CLIENT_SECRET_KEY}
    volumes:
      - ./config.json:/app/config.json
    networks:
      - api
      - api-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
  public-api_nginx:
    image: nginx
    container_name: public-api_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
      - api-proxy
    depends_on:
      - public-api
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.public-api_nginx.loadbalancer.server.port=14100"
      - "traefik.http.routers.public-api_nginx.rule=Host(`api.salvatoreemilio.it`) || Host(`www.api.salvatoreemilio.it`)"
      - "traefik.http.routers.public-api_nginx.tls.certresolver=myresolver"
      - "traefik.http.routers.public-api_nginx.entrypoints=websecure"
      - "traefik.docker.network=se-default"

networks:
  default:
    external: true
    name: se-default
  api:
    external: true
    name: se-api
  api-proxy:
    external: true
    name: se-api-proxy
