version: "3.8"

services:
  nginx:
    image: salvatoreemilio/salvatoreemilio.it_frontend:latest
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=15000"
      - "traefik.http.routers.nginx.rule=Host(`salvatoreemilio.it`) || Host(`www.salvatoreemilio.it`)"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"
      - "traefik.http.routers.nginx.entrypoints=websecure"

networks:
  default:
    external: true
    name: se_default
