version: "3.8"

services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb
    restart: unless-stopped
    volumes:
      - ./rethinkdb.conf:/etc/rethinkdb/default.conf
      - se-api-rethinkdb:/data
    command: rethinkdb --config-file /etc/rethinkdb/default.conf
    networks:
      - api-db
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"

volumes:
  se-api-rethinkdb:
    external: true

networks:
  api-db:
    external: true
    name: se-api-db
