version: "3.8"

services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb
    restart: unless-stopped
    volumes:
      - ./rethinkdb.conf:/etc/rethinkdb/default.conf
      - rethinkdb_data:/data
    command: rethinkdb --config-file /etc/rethinkdb/default.conf
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"

volumes:
  rethinkdb_data:
    external: true

networks:
  default:
    external: true
    name: se_default
