global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:11050"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:11030"]
