version: "3.8"

services:
  nginx:
    image: nginx:1.23.2
    container_name: curtnativeandroidclient-privacy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.curtnativeandroidclient-privacy.loadbalancer.server.port=19900"
      - "traefik.http.routers.curtnativeandroidclient-privacy.rule=Host(`curtnativeandroidclient.privacy.salvatoreemilio.it`) || Host(`www.curtnativeandroidclient.privacy.salvatoreemilio.it`)"
      - "traefik.http.routers.curtnativeandroidclient-privacy.tls.certresolver=myresolver"
      - "traefik.http.routers.curtnativeandroidclient-privacy.entrypoints=websecure"
      - "traefik.docker.network=se-default"

networks:
  default:
    external: true
    name: se-default
