version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      --skip-innodb-read-only-compressed=OFF
    volumes:
      - se-nextcloud-mariadb:/var/lib/mysql
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
      - MYSQL_TCP_PORT=13030
      - MYSQL_UNIX_PORT=13031
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=qwerty
      - MYSQL_DATABASE=nextcloud
    networks:
      - nextcloud
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"

  nextcloud:
    image: nextcloud:fpm-alpine
    container_name: nextcloud
    restart: always
    volumes:
      - se-nextcloud:/var/www/html
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    environment:
      - OVERWRITEPROTOCOL=https
      - MYSQL_PASSWORD=qwerty
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb:13030
    depends_on:
      - mariadb
    networks:
      - nextcloud
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"

  nextcloud_nginx:
    image: nginx
    container_name: nextcloud_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - nextcloud
    networks:
      - default
      - nextcloud
    depends_on:
      - nextcloud
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nextcloud_nginx.loadbalancer.server.port=15010"
      - "traefik.http.routers.nextcloud_nginx.rule=Host(`cloud.salvatoreemilio.\
        it`) || Host(`www.cloud.salvatoreemilio.it`)"
      - "traefik.http.routers.nextcloud_nginx.tls.certresolver=myresolver"
      - "traefik.http.routers.nextcloud_nginx.entrypoints=websecure"
      - "traefik.docker.network=se-default"

  nextcloud_cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud_cron
    restart: always
    volumes:
      - se-nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - mariadb
    networks:
      - nextcloud
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"

volumes:
  se-nextcloud-mariadb:
    external: true
  se-nextcloud:
    external: true

networks:
  default:
    external: true
    name: se-default
  nextcloud:
    external: true
    name: se-nextcloud
