version: "3.8"

services:
  internal-api:
    image: salvatoreemilio/salvatoreemilio.it_internal-api:latest
    container_name: internal-api
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"

networks:
  default:
    external: true
    name: se_default
