version: "3.8"

services:
  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboard.json:/data/dashboard.json
    environment:
      - GF_SERVER_HTTP_PORT=11000
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GRAFANA_AUTH_CLIENT_SECRET}
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_OAUTH_AUTO_LOGIN=true
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Keycloak OAuth
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana-auth
      - GF_AUTH_GENERIC_OAUTH_SCOPES=profile
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://login.salvatoreemilio.it/realms/se/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://login.salvatoreemilio.it/realms/se/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://login.salvatoreemilio.it/realms/se/protocol/openid-connect/userinfo
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(roles[*], 'admin') &&
        'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
      - GF_SERVER_ROOT_URL=https://grafana.salvatoreemilio.it
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=data/dashboard.json
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=11000"
      - "traefik.http.routers.grafana.rule=Host(`grafana.salvatoreemilio.it`) ||
        Host(`www.grafana.salvatoreemilio.it`)"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.routers.grafana.entrypoints=websecure"

volumes:
  grafana_data:
    external: true

networks:
  default:
    external: true
    name: se_default
