version: "3.8"

services:
  private-api:
    image: salvatoreemilio/salvatoreemilio.it_private-api:latest
    container_name: private-api
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
    networks:
      - api
      - api-db
    depends_on:
      - private-api-rethinkdb
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
  private-api-rethinkdb:
    image: rethinkdb:2.4.2
    container_name: private-api-rethinkdb
    restart: unless-stopped
    volumes:
      - ./rethinkdb.conf:/etc/rethinkdb/default.conf
      - se-api-rethinkdb:/data
    command: rethinkdb --config-file /etc/rethinkdb/default.conf
    networks:
      - api-db
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"

volumes:
  se-api-rethinkdb:
    external: true

networks:
  api:
    external: true
    name: se-api
  api-db:
    external: true
    name: se-api-db
