name: CI/CD internal-api

on:
  push:
    branches: [ dev ]
    paths:
      - "api/internal/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/internal
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: api/internal
          file: api/internal/dockerfile
          push: true
          tags: salvatoreemilio/salvatoreemilio.it_internal-api:latest,salvatoreemilio/salvatoreemilio.it_internal-api:0.0.1
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
     - name: executing remote ssh commands using ssh key
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: sh salvatoreemilio.it/api/internal/cd.sh
