# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: SSH setup 
          run: |
            echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan "${{secrets.SSH_HOST}}" >> ~/.ssh/known_hosts

        - name: Deploy
          run: |
            ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{secrets.SSH_PORT}} "
              docker-compose down;
              docker-compose pull;
              docker-compose up -d;
            "
        - name: Cleanup
          run: rm -rf ~/.ssh/id_rsa
